import{SERVICES,TYPES,normalize,readImport,mergeImport,filterItems,csv}from'./model.js';
const $=s=>document.querySelector(s),KEY='swo.web.v1';let items=[],editing=null,timer;const filters={service:'all',type:'all',status:'all',query:'',sort:'added'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(text){$('#notice').textContent=text;$('#notice').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#notice').style.display='none',4500)}
let storageBroken=false;
try{const raw=localStorage.getItem(KEY);if(raw)items=readImport(JSON.parse(raw))}catch{storageBroken=true;notify('保存データを読み込めません。元データを保護するため、変更を停止しました。')}
function save(next){if(storageBroken){notify('元データの読み込みに失敗したため保存できません。');return false}try{localStorage.setItem(KEY,JSON.stringify({schema:'swo-web',version:1,items:next}));items=next;render();return true}catch{notify('保存できませんでした。ブラウザの保存容量・設定を確認してください。');return false}}
function render(){
 $('#services').innerHTML=Object.entries({all:'すべてのサービス',...SERVICES}).map(([key,name])=>`<button data-service="${key}" class="${filters.service===key?'active':''}" aria-pressed="${filters.service===key}">${name}<span>${items.filter(i=>key==='all'||i.service===key).length}</span></button>`).join('');
 $('#types').innerHTML=['all',...TYPES].map(t=>`<button data-type="${t}" class="${filters.type===t?'active':''}" aria-pressed="${filters.type===t}">${t==='all'?'すべて':t}</button>`).join('');
 const list=filterItems(items,filters);$('#count').textContent=String(list.length).padStart(2,'0');$('#summary').textContent=`観たい ${items.filter(i=>!i.watched).length} / 視聴済み ${items.filter(i=>i.watched).length}`;
 $('#grid').innerHTML=list.length?list.map(i=>`<article class="card"><div class="cover" data-type="${i.type}"><small>${esc(i.type)} / PERSONAL COLLECTION</small><strong>${esc(i.title)}</strong></div><div class="card-body"><div class="meta"><span class="service">${SERVICES[i.service]}</span><span>${esc(i.genre)}</span></div><p class="memo">${esc(i.memo||'まだ、出会っていない物語。')}</p><div class="card-actions"><button data-watch="${esc(i.id)}" aria-pressed="${i.watched}">${i.watched?'✓ 視聴済み':'○ 観たい'}</button><button data-edit="${esc(i.id)}" aria-label="${esc(i.title)}を編集">編集</button><span class="stars" aria-label="3点中${i.star}点">${'★'.repeat(i.star)}${'☆'.repeat(3-i.star)}</span></div><div class="links">${i.href?`<a href="${esc(i.href)}" target="_blank" rel="noopener noreferrer">サービスで開く ↗</a>`:''}<a href="https://www.themoviedb.org/search?query=${encodeURIComponent(i.title)}" target="_blank" rel="noopener noreferrer">TMDb ↗</a><a href="https://www.justwatch.com/jp/検索?q=${encodeURIComponent(i.title)}" target="_blank" rel="noopener noreferrer">配信を探す ↗</a></div></div></article>`).join(''):`<div class="empty"><h3>${items.length?'条件に合う作品がありません':'あなたの最初の一本から。'}</h3><p>${items.length?'検索語や絞り込みを変えてみてください。':'「作品を追加」から登録するか、拡張機能のJSONバックアップを取り込んでください。'}</p>${items.length?'<button id="reset">絞り込みをリセット</button>':'<button id="first" class="primary">＋ 最初の作品を追加</button>'}</div>`;
}
function openEditor(id=null){editing=id;const i=items.find(i=>i.id===id);$('#form').reset();$('#editor-title').textContent=i?'作品の記録':'作品を追加';$('#delete').hidden=!i;if(i)for(const key of ['title','type','service','genre','href','watched','star','memo'])$('#form').elements.namedItem(key).value=String(i[key]);$('#editor').showModal();$('#form').elements.namedItem('title').focus()}
$('#services').onclick=e=>{const b=e.target.closest('[data-service]');if(b){filters.service=b.dataset.service;render()}};
$('#types').onclick=e=>{const b=e.target.closest('[data-type]');if(b){filters.type=b.dataset.type;render()}};
$('#search').oninput=e=>{filters.query=e.target.value;render()};for(const key of ['status','sort'])$('#'+key).onchange=e=>{filters[key]=e.target.value;render()};
$('#grid').onclick=e=>{const watch=e.target.closest('[data-watch]'),edit=e.target.closest('[data-edit]');if(watch)save(items.map(i=>i.id===watch.dataset.watch?{...i,watched:!i.watched}:i));if(edit)openEditor(edit.dataset.edit);if(e.target.id==='first')openEditor();if(e.target.id==='reset'){Object.assign(filters,{service:'all',type:'all',status:'all',query:''});$('#search').value='';$('#status').value='all';render()}};
$('#add').onclick=()=>openEditor();$('#close').onclick=()=>$('#editor').close();$('#editor').onclick=e=>{if(e.target===$('#editor')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
$('#form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(data.href&&!/^https?:\/\//i.test(data.href)){notify('URLは https:// または http:// から入力してください。');return}try{const old=items.find(i=>i.id===editing);const item=normalize({...old,...data,watched:data.watched==='true'});if(save(editing?items.map(i=>i.id===editing?item:i):[...items,item])){$('#editor').close();notify('ライブラリに保存しました')}}catch(err){notify(err.message)}};
$('#delete').onclick=()=>{if(confirm('この作品と評価・メモを削除しますか？')&&save(items.filter(i=>i.id!==editing)))$('#editor').close()};
$('#random').onclick=()=>{const choices=filterItems(items,{...filters,status:'unwatched'});if(!choices.length)return notify('現在の検索・分類条件に未視聴の作品がありません。');const item=choices[Math.floor(Math.random()*choices.length)];openEditor(item.id);$('#editor-title').textContent='今夜の一本 — '+item.title};
function download(text,type,name){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#csv').onclick=()=>download(csv(filterItems(items,filters)),'text/csv;charset=utf-8','swo-watchlist.csv');
$('#backup').onclick=()=>download(JSON.stringify({schema:'swo-web',version:1,items},null,2),'application/json','swo-backup.json');
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('ファイルは10MB以下にしてください。');const incoming=readImport(JSON.parse(await file.text()));if(!incoming.length)return notify('取り込む作品がありません。');if(confirm(`${incoming.length}件を取り込みます。同じIDまたは同じサービス・URLの作品は、取り込むデータで更新します。続けますか？`)&&save(mergeImport(items,incoming)))notify(`${incoming.length}件を取り込みました。`)}catch(err){notify(err.message)}finally{e.target.value=''}};
window.addEventListener('storage',e=>{if(e.key===KEY){try{items=e.newValue?readImport(JSON.parse(e.newValue)):[];render()}catch{notify('別タブの更新を読み込めませんでした。')}}});render();
