import test from 'node:test';import assert from 'node:assert/strict';import{normalize,readImport,readCSV,mergeImport,mergeSynced,filterItems,csv,safeURL}from'./model.js';
const a=normalize({title:'A',service:'prime',href:'https://example.com/a',genre:'アニメ',star:2,memo:'一行目\n"二行目"'});
test('extension migration preserves personal records and category',()=>{const imported=readImport({swo_prime_items:[a],swo_userdata:{[a.href]:{watched:true,star:3,memo:'感想'}}});assert.equal(imported[0].memo,'感想');assert.equal(imported[0].star,3);assert.equal(imported[0].type,'アニメ');assert.equal(imported[0].watched,true)});
test('backup round trip and duplicate import update',()=>{assert.deepEqual(readImport(JSON.parse(JSON.stringify({schema:'swo-web',version:1,items:[a]}))),[a]);const merged=mergeImport([a],[{...a,id:'other',memo:'更新'}]);assert.equal(merged.length,1);assert.equal(merged[0].id,a.id);assert.equal(merged[0].memo,'更新')});
test('filters intersect across service, category, status and memo',()=>{const items=[a,normalize({title:'B',service:'netflix',type:'映画',watched:true})];assert.equal(filterItems(items,{service:'prime',type:'アニメ',status:'unwatched',query:'二行目'}).length,1);assert.equal(filterItems(items,{service:'netflix',type:'アニメ'}).length,0)});
test('untrusted import URL, rating and service validation',()=>{assert.equal(safeURL('javascript:alert(1)'), '');assert.equal(normalize({...a,star:99}).star,3);assert.throws(()=>normalize({...a,service:'__proto__'}));assert.throws(()=>readImport({items:[a]}));assert.throws(()=>readImport({schema:'swo-web',version:1,items:[a,{title:42}]}))});
test('CSV quotes multiline values and guards formula injection',()=>{const result=csv([{...a,title:'=1+1'}]);assert.ok(result.includes('"\'=1+1"'));assert.ok(result.includes('"一行目\n""二行目"""'))});
test('CSV import accepts extension export columns and multiline memo',()=>{const text='\uFEFFタイトル,種類,ジャンル,サービス,視聴済み,★評価,メモ,URL\r\n"作品A",アニメ,アニメ,Netflix,済み,★★,"一行目\n二行目",https://example.com/a';const [item]=readCSV(text);assert.equal(item.title,'作品A');assert.equal(item.service,'netflix');assert.equal(item.watched,true);assert.equal(item.star,2);assert.equal(item.memo,'一行目\n二行目')});
test('cloud merge keeps newer records and applies newer tombstones',()=>{const local={...a,updatedAt:10};const remote={...a,title:'remote',updatedAt:20};assert.equal(mergeSynced([local],[remote],[])[0].title,'remote');assert.equal(mergeSynced([remote],[],[{id:a.id,updatedAt:21}]).length,0)});
